name: container-hepa-ghcr
on:
  push:
    branches:
      - main
      - bnewbold/automod
    tags:
      - "hepa-v*"
jobs:
  container-hepa-ghcr:
    if: github.repository == 'bluesky-social/indigo'
    permissions:
      contents: read
      packages: write
      id-token: write

    uses: ./.github/workflows/build-ghcr-container.yaml
    with:
      namespace: ${{ github.repository }}
      image_name: hepa
      dockerfile: ./cmd/hepa/Dockerfile
    secrets: inherit
